config/routes.rb
DemoApp::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}

  scope '(:locale)' do
    root 'users/posts#index'

    namespace :users do
      resources :posts, only: [:index,:show] do
        resource :comments
      end
      resources :about, only: [:index]
      resources :users, path:'current_user'
    end
  end

  namespace :admin do
    post 'login' => 'home#login'
    get 'login' => 'home#login'
    resources :posts
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :text ,presence: true


  scope :order_desc, -> {order('created_at DESC')}

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :name,presence: true

  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :title ,presence: true
  validates :text ,presence: true



  belongs_to :user
  has_many :comments , dependent: :destroy
  has_many :images

  scope :order_desc, -> {order('created_at DESC')}

  def self.search(search)
    #binding.pry;
      where(['text || title LIKE ?', "%#{search}%"])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  mount_uploader :avatar, ImageUploader

  has_many :posts
  has_many :comments
  has_many :images

  def name
   "#{first_name}" +' '+ "#{last_name}"
  end

end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ActionController::Base

    before_filter :is_admin_pwd?, :except => [:login]

    layout 'admin'


    def is_admin_pwd?
      unless session[:admin]
        redirect_to admin_login_path
      end
    end

  end
end

app/controllers/admin/home_controller.rb
module Admin
class HomeController  < Admin::AdminController

  skip_before_filter  :verify_authenticity_token
  layout false

  def login
    if params[:pwd].present? &&
        Digest::SHA2.hexdigest(params[:pwd]) == 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3'
      session[:admin] = true
      redirect_to   admin_posts_path
    end
  end

  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::AdminController

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    if @post.save
      redirect_to [:admin,@post], notice: 'create successfully'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(posts_params)
      redirect_to [:admin,@post],notice: 'updated successfully'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
     @post.destroy
    respond_to do |format|
      format.html{ }
      format.js
    end
  end

  private

  def posts_params
    params.require(:post).permit(:text,:title,:theme,:image)
  end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_filter :set_il8n_locale_from_params
  after_filter :store_location


  def store_location
    session[:previous_url] = request.fullpath
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_sign_out_path_for(resource)
    session[:previous_url] || root_path
  end
  protected

  def set_il8n_locale_from_params
    if params[:locale]
      if I18n.available_locales.include?(params[:locale].to_sym)
        I18n.locale = params[:locale]
        else
        flash.now[:notice ] = "#{params[:locale]} translation not available "
       logger.error flash.now[:notice]
      end
      end
  end

  def default_url_options
  { locale:  I18n.locale }
  end

end

app/controllers/users/about_controller.rb
module Users
 class AboutController < ApplicationController

  def index
  end

  end
end

app/controllers/users/comments_controller.rb
module Users
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_params)

    if @comment.save
      redirect_to [:users,@post],notice: 'Commented'
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @comment = @post.comments.delete
  end


  private

  def comments_params
    all_params = params.require(:comment).permit(:text, :user_id,:rate)
    all_params[:user_id] = current_user.id  if current_user
    all_params
  end
end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController


    def index
      if params[:set_locale]
        redirect_to root_url(locale: params[:set_locale])
      else
        @posts = Post.all.order_desc.search(params[:search]).page(params[:page]).per(5)
        @newest = Post.last(5)
      end
    end

    def show
      @comments = Comment.create(params[:text])
      @post = Post.find(params[:id])
      @post_comments = @post.comments.order_desc
    end


    def new
      @post = Post.new
    end

    def create
      @post = Post.new(posts_params)
      if @post.save
        redirect_to [:user,@post], notice: 'create successfully'
      else
        render :new
      end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(posts_params)
        redirect_to [:user,@post],notice: 'updated successfully'
      else
        render :new
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy


    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController <  Devise::RegistrationsController

  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController <  Devise::SessionsController




  end
end

app/controllers/users/users_controller.rb
module Users
  class UsersController < ApplicationController
    #before_action :authenticate_user!

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(users_params)
        render 'show', notice: t('update_success')
      else
        render 'edit' ,alert: t('update_success')
      end
    end



    private

    def users_params
     params.require(:user).permit(:first_name,:last_name,:email,:avatar,:password)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end


  def validation_errors(model)
    if model.errors.any?
      content_tag :div, model.errors.full_messages.to_sentence, class: 'alert alert-danger'
    end
  end
end

app/views/admin/home/login.html.erb
Admin Login
<form method="post" >
  Password: <input type="password" name="pwd">
  <input type="submit">
</form>

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post], html: {role: 'form', class: 'form-horizontal'} do |f| %>

    <%= validation_errors(@post)%>

    <div class="form-group">
      <%= f.label :title, class: 'col-sm-1 required' %>
      <div class="col-sm-5">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :theme, class: 'col-sm-1 required' %>
      <div class="col-sm-5">
        <%= f.text_field :theme, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :text, class: 'col-sm-1 required' %>
      <div class="col-sm-5">
        <%= f.text_area :text, size: '5x5', class: 'form-control' %>

        <div class="form-group">
          <%= f.label :image, class: 'col-sm-1' do %>

          <% end %>
          <div class="col-sm-3">

          </div>
          <div class="col-sm-5" >
            <%= f.file_field :image ,class:'form-control'%>

          </div>
        </div>

      </div>
    </div>
    <div class="panel-footer">
    <%= f.submit 'Add Post', class: 'btn ' %>
      <%= link_to 'Back', request.referer, class: 'btn btn-warning' %>

    </div>
<% end %>

app/views/admin/posts/destroy.js.erb
$('#<%= @post.id %>').fadeOut('3000');

app/views/admin/posts/edit.html.erb
<%= render 'form'%>

app/views/admin/posts/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Image</th>
    <th>Delete</th>
  </tr>
  <% @posts.each do |p| %>

      <tr id="<%=p.id%>">

        <td><%= link_to p.title, admin_post_path(p) %></td>
        <td><%=p.text %></td>
        <td><%=image_tag(p.image_url(:tiny)) %></td>
          <td>
         <%= link_to 'Delete', [:admin, p], method: :delete,
                         class: 'btn btn-danger btn-xs',remote: true   %> </td>
      </tr>
  <% end %>
</table>
<div class="panel-footer">
  <%= link_to 'Add Post',new_admin_post_path,class:'btn btn-primary'%>
        </div>

app/views/admin/posts/new.html.erb
<%= render 'form'%>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <h2 class="lead" style="text-align: center"><%= @post.title %></h2>
      <div class="panel-body">
        <%= @post.text %>
        <%= image_tag @post.image_url(:thumbnail),style:'float: left'%>
        <hr>
        <%= link_to 'Edit',edit_admin_post_path(@post),class:'btn btn-primary'%>
          </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to t('.posts'),admin_posts_path %></li>
      </ul>
      </div>
  </nav>




<% if notice.present? %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert.present? %>
    <div class="alert alert-danger"><%= alert %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to t('.posts'),users_posts_path %></li>
        <li><%= link_to t('.about'),users_about_index_path %></li>
        <li><a href="https://github.com/stasyanx/demo_app/tree/master"><%=t('.git')%></a></li>
      </ul>
      <div class="pull-right" id="login">
      <% if current_user.blank? %>
          <button class="btn " data-toggle="modal" data-target="#signin">
           <%=t('.sign_in')%>
          </button>
          <%= t('.or')%>
          <button class="btn " data-toggle="modal" data-target="#signup">
           <%=t('.sign_up')%>
          </button>
      <% else %>

            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                  <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                    <i class="glyphicon glyphicon-user"></i> <%= current_user.try(:name)%><span class="caret"></span></a>
                  <ul id="g-account-menu" class="dropdown-menu" role="menu">
                    <li><%= link_to t('.profile'),users_user_path(current_user.id)%></li>
                    <li><%= link_to  destroy_user_session_path, method: :delete do %>
                          <i class="glyphicon glyphicon-lock"><%=t('.logout')%></i>
                          <%end%>
                          </li>
                  </ul>
                </li>
              </ul>
            </div>

      <% end %>
        </div>
      <div class="col-sm-1" id="locale">
      <%= form_for root_path , method: :get do %>
       <%= select_tag :set_locale ,
             options_for_select( LANGUAGES, I18n.locale.to_s ) ,
             onchange: 'this.form.submit()',class:'form-control' %>


       <% end %>
      </div>
          <div class="login"> <!-- Button trigger modal -->
            <!-- Modal -->
            <div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel"><%=t('.sign_in')%></h4>
                  </div>
                  <div class="modal-body">
                                <%=render template:'devise/sessions/new'%>
                  </div>

                </div>
              </div>
            </div>
          </div>
      <!-- Modal -->
      <div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel"><%=t('.sign_up')%></h4>
            </div>
            <div class="modal-body">
              <%=render template:'devise/registrations/new'%>
            </div>

          </div>
        </div>
      </div>
    </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert.present? %>
    <div class="alert alert-danger"><%= alert %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/about/index.html.erb
<div style="padding-left: 20px">
<h1 style="text-align: center"><b>Stanislav Nosovskiy</b></h1>

Kharkov <br/>
Cell: 0934247448  <br/>
E-Mail: mypostboxst@gmail.com <br/>
 <hr>

  <h3><b>Highlights</b></h3>
<ul>
  <li>Ruby</li>
  <li>Ror</li>
  <li>Ajax</li>
  <li>Cloudinary API</li>
  <li>Mapbox API</li>
  <li>git</li>
  <li>Html</li>
  <li>Css</li>
  <li>Bootstrap</li>
  <li>Jquery</li>
  </ul>

  <hr>
    <h3><b>Experience</b></h3>

October 2013 to June 2014 <br/>
Company name: Inservery  <br/>
Jr software developer  <br/>
<a href="inservery.com">Inservery</a><br/>
  <hr>
      <h3><b>Summary</b></h3>

Have a passion to learn new cool features<br/>
Familiarity with the MVC model,testing,popular Gems <br/>
  <hr>
        <h3><b>Language skills</b></h3>

English: pre-intremediate <br/>
Russian:   native speaker <br/>
Ukrainian:  native speaker<br/>

</div>

app/views/users/comments/_form.html.erb
<%= form_for @comments do|f|%>
    <%= f.text_field :text %>
    <%=f.submit 'save'%>
<% end %>

app/views/users/comments/create.js.erb
<% if @comment.new_record?%>
    $('#comment_text').effect('highlight', {color: 'red'});
<% else %>
    $('#comments').html('<%= j render @comment %>').effect('highlight', {}, 3000);
<% end %>

app/views/users/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h1><b><%= t('.demo_app') %></b></h1>
      <% @posts.each do |p| %>
          <!-- blog entry -->

          <h1><%= link_to p.title, users_post_path(p) %>   </h1>
          <% if p.user.present? %>
              <p class="lead"><%= t('.by') %> <%= p.user.try(:name) %>
          <% end %>
          <hr>
          <p>
            <span class="glyphicon glyphicon-time"></span><%= t('.posted') %> <%= time_ago_in_words p.created_at %> <%= t('.ago') %>
          </p>

          <p><em><%= t('.comments') %> <%= p.comments.count %> </em></p>
          <% if p.image_url(:standard).blank? %>
              <img src="http://placehold.it/750x350" class="img-responsive">
          <% else %>
              <hr>     <%= link_to (image_tag p.image_url(:standard)), users_post_path(p) %>
          <% end %>
          <p> <%= p.text %></p>

          <a class="btn btn-primary" href="<%= users_post_path(p) %>">
            <%= t('.read_more') %><span class="glyphicon glyphicon-chevron-right"></span></a>

          <hr>
      <% end %>



      <!-- pager -->
      <ul class="pagination" style="margin: 0px !important; padding-left: 10px">
        <%= paginate @posts %>
      </ul>

    </div>

    <div class="col-lg-4">
      <div class="well">
        <h4><%= t('.search') %></h4>
        <% if params[:search] %>
            <b><%= 'Results found:' "#{@posts.size}" %></b>
        <% end %>
        <div class="input-group">

          <%= form_tag users_posts_path, method: 'get' do %>
                  <span class="input-group-btn">
                <%= text_field_tag :search, params[:search], class: 'form-control' %>
                    <%= button_tag '', :name => nil, class: 'btn btn-default' do %>
                            <span class="glyphicon glyphicon-search"></span>
                            <% end %>
                     </span>
          <% end %>
        </div>
        <!-- /input-group -->
      </div>
      <!-- /well -->
      <div class="row">
        <div class="col-md-12">

          <div class="well">
            <h4><%= t('.latest_posts') %> </h4>
            <ol>
              <% @newest.each do |p| %>
                  <li style="padding: 10px"> <%= link_to p.title, users_post_path(p) %>
                    <br/>  </li>


              <% end %>
            </ol>
          </div>
        </div>
      </div>

      <!-- /well -->
      <div class="well">
        <h4>Side Widget Well</h4>

        <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
      </div>
      <!-- /well -->
    </div>
  </div>

  <hr>

  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Company 2013</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

app/views/users/posts/new.html.erb
<%= render 'form'%>

app/views/users/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <h2 class="lead" style="text-align: center"><%= @post.title %></h2>

      <div class="panel-body">
        <%= @post.text %>
        <hr>
                    <button class="btn btn-info">
                      <i class="glyphicon glyphicon-comment"></i><%=t('.comment')%></button>
        <div class="well" id="coment-well">
          <%= form_for [:users,@post, Comment.new], html: {role: 'form', class: 'form-horizontal'} do |f| %>
              <div class="form-group">
                <%= f.text_area :text, size: '5x5', class: 'form-control' %>

              </div>
              <%= f.submit t('.comment'), class: 'btn btn-primary' ,id:'comment' %>
          <% end %>
        </div>

        <hr>

        <div id="comments">
          <% if @post.comments.blank? %>
              <div class="alert alert-info"><%= t('.no_comment')%></div>
          <% else %>
              <% @post_comments.each do |c| %>

                  <h3> <%=link_to c.user.try(:name) ,users_user_path(c.user_id) if (c.user_id) %>
                    <small><%= time_ago_in_words c.created_at %> ago</small>
                  </h3>
                  <p><%= c.text %> </p>
              <% end %>
              </div>
          <% end %>

          </div>
    </div>
  </div>
</div>

app/views/users/users/_form.html.erb
<div class="row">
  <div class="col-md-8" style='padding-top:20px'>

    <%= form_for [:users, @user], html: {role: 'form', class: 'form-horizontal'} do |f| %>

        <%= validation_errors(@user) %>
        <div class="form-group">
          <%= f.label :first_name, class: 'col-sm-3 required' %>
          <div class="col-sm-3">
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :last_name, class: 'col-sm-3 required' %>
          <div class="col-sm-3">
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, class: 'col-sm-3 required' %>
          <div class="col-sm-3">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>

        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :avatar, class: 'col-sm-4 required' %>
            <div class="col-sm-5">
              <%= image_tag @user.avatar_url(:thumbnail) %>
              <%= f.file_field :avatar, class: 'form-control' %>
            </div>
          </div>
        </div>

        </div>

        <div class="panel-footer">
          <%= f.submit t('.submit'), class: 'btn btn-default ' %>
        </div>

    <% end %>

app/views/users/users/edit.html.erb
<%= render 'form'%>

app/views/users/users/show.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <ul class="nav nav-tabs" id="users">
        <li class="active"><a href="#profile"><%=t('.profile')%></a></li>
        <li><a href="#messages"><%=t('.comments')%></a></li>
        <% if current_user.try(:name) == @user.name %>
        <li><a href="#settings"><%=t('.settings')%></a></li>
        <%end%>
      </ul>



      <div class="tab-content">
        <div class="tab-pane active" class="tab-pane" id="profile">
          <h2><%= @user.name %></h2>
          <b><%= t('.lastsignin') %></b>
          <%= @user.last_sign_in_at.try(:strftime,(" %m/%d/%Y %I:%M")) %> <br/>
          <b><%= t('.created_at') %></b>
          <%= @user.created_at.try(:strftime,(" %m/%d/%Y %I:%M"))   %>    <br/>
           <%= image_tag @user.avatar_url(:thumbnail), class: "center-block img-circle img-responsive" %>
        </div>


  <div class="tab-pane" id="messages">
    <% @user.comments.each do |c|%>
    <%= link_to  c.text, users_post_path(c.post_id)%><br/>
        <%= t('.at_theme')%> <%=link_to  c.post.title,users_post_path(c.post_id)%>
        <%= time_ago_in_words c.created_at  %> <br/>
            <hr>
        <%end%>
  </div>

  <div class="tab-pane" id="settings">
    <%= render 'form' %>
  </div>

      </div>
    </div>
  </div>

</div>